/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ItemsImport } from './routes/items'
import { Route as InfoImport } from './routes/info'
import { Route as IndexImport } from './routes/index'
import { Route as ItemsItemIdImport } from './routes/items_.$itemId'

// Create/Update Routes

const ItemsRoute = ItemsImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRoute,
} as any)

const InfoRoute = InfoImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ItemsItemIdRoute = ItemsItemIdImport.update({
  id: '/items_/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoImport
      parentRoute: typeof rootRoute
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsImport
      parentRoute: typeof rootRoute
    }
    '/items_/$itemId': {
      id: '/items_/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof ItemsItemIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/items': typeof ItemsRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/items': typeof ItemsRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/items': typeof ItemsRoute
  '/items_/$itemId': typeof ItemsItemIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/info' | '/items' | '/items/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/info' | '/items' | '/items/$itemId'
  id: '__root__' | '/' | '/info' | '/items' | '/items_/$itemId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InfoRoute: typeof InfoRoute
  ItemsRoute: typeof ItemsRoute
  ItemsItemIdRoute: typeof ItemsItemIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InfoRoute: InfoRoute,
  ItemsRoute: ItemsRoute,
  ItemsItemIdRoute: ItemsItemIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/info",
        "/items",
        "/items_/$itemId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/info": {
      "filePath": "info.tsx"
    },
    "/items": {
      "filePath": "items.tsx"
    },
    "/items_/$itemId": {
      "filePath": "items_.$itemId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
